### ISSUE TITLE
Bioconda CDN sync down

### ISSUE THREAD

**Issue by dpryan79** [conda/infrastructure#764] opened 2023-05-12 19:37 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The CDN sync for the bioconda seems to have been down for ~24 hours so far. For example, new packages under https://anaconda.org/bioconda/r-recetox-aplcms/files aren't available via `conda install`.

### Conda Info

```shell
NA
```

### Conda Config

```shell
NA
```

### Conda list

```shell
NA
```

**Comment by tnabtaf** [comment] 2023-05-12 23:49
Reported, late on a Friday that was a holiday at Anaconda.  We'll see.

**Comment by dpryan79** [comment] 2023-05-14 20:11
@gmjen I'm part of the bioconda core team, I'm well aware of how channels and dependencies work. The CDN sync has been down since May 11th.

**Comment by barabo** [comment] 2023-05-15 00:47
The bioconda clone starts up every 20 minutes, runs, then shuts itself down (when working as intended).  A few days ago the machine experienced a hardware failure while starting up that left it in a bad state, blocking further runs from starting.  We had an issue like this a week ago with the pytorch channel, and had not yet rolled out the fix.

I'm escalating the patch and will deploy it once the PR has been approved and merged.

In the meantime, I restarted the bioconda clone and it is catching up now.  It should finish within the next 20 minutes.

**Comment by johanneskoester** [comment] 2023-05-15 05:54
Thanks a lot!

**Comment by jezdez** [comment] 2023-05-15 09:59
This seems to have been fixed, thanks @barabo!

**Closed by jezdez** 2023-05-15 09:59 UTC
Labels: type::bug
