### ISSUE TITLE
CDN sync seems to be slower than usual this week

### ISSUE THREAD

**Issue by leofang** [conda/infrastructure#740] opened 2023-04-06 00:45 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

CDN sync seems to be slower than usual this week. Taking `libcublas` as example
<img width="1018" alt="截圖 2023-04-05 下午8 42 23" src="https://user-images.githubusercontent.com/5534781/230244482-af635ded-1052-4da4-901e-21a808ce4abd.png">
I started monitoring the status via `conda search --platform linux-aarch64 libcublas` after [this PR](https://github.com/conda-forge/libcublas-feedstock/pull/6) is merged and the copy to the conda-forge channel is done, and as shown above it took ~47 mins for `conda search` to find it. IIRC the CDN sync time has been significantly reduced to 15-30 mins before, so this is a bit concerning.

### Conda Info

```shell
$ conda info

     active environment : opt_einsum_dev
    active env location : /home/leof/miniforge3/envs/opt_einsum_dev
            shell level : 2
       user config file : /home/leof/.condarc
 populated config files : /home/leof/miniforge3/.condarc
                          /home/leof/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.31=0
                          __linux=5.8.0=0
                          __unix=0=0
       base environment : /home/leof/miniforge3  (writable)
      conda av data dir : /home/leof/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/leof/miniforge3/pkgs
                          /home/leof/.conda/pkgs
       envs directories : /home/leof/miniforge3/envs
                          /home/leof/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.9.16 Linux/5.8.0-53-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1019:1019
             netrc file : None
           offline mode : False
```
```


### Conda Config

```shell
$ conda config --show-sources
==> /home/leof/miniforge3/.condarc <==
channels:
  - conda-forge

==> /home/leof/.condarc <==
channels:
  - conda-forge
```
```


### Conda list

_No response_

### Additional Context

_No response_

**Comment by leofang** [comment] 2023-04-06 00:45
cc: @jakirkham

**Comment by barabo** [comment] 2023-04-06 13:29
I'm looking into an issue with one of the Cloudflare caches.  It seems that it only caches `.tar.bz2` files (we forgot to add `.conda` when we started putting conda files in the repo for `conda-forge`), so `.conda` downloads would likely be much slower.

**Comment by jakirkham** [comment] 2023-04-06 15:14
Ah ok. This makes much more sense. Thanks Carl! 🙏

**Comment by jakirkham** [comment] 2023-04-07 01:40
Recently saw an issue where a package, `libnvjitlink`, uploaded binaries for Linux and Windows at roughly the same time. However the Windows package mirrored much slower.

<hr>

<details>
<summary>
Screenshot showing Linux and Windows packages
</summary>

<img width="1840" alt="Screen Shot 2023-04-06 at 6 35 19 PM" src="https://user-images.githubusercontent.com/3019665/230522643-55bbc395-6b36-432c-86d5-c80a0628d45f.png">

Note: Download count is `1` because I did a download from the web UI.
</details>


<details>
<summary>
Searching for Linux package
</summary>

```
$ conda search 'libnvjitlink[channel=conda-forge, subdir=linux-64]'
Loading channels: done
# Name                       Version           Build  Channel             
libnvjitlink                 12.0.76      hcb278e6_0  conda-forge
```

</details>

<details>
<summary>
Searching for Windows package
</summary>

```
$ conda search 'libnvjitlink[channel=conda-forge, subdir=win-64]'
Loading channels: done
No match found for: conda-forge/win-64::libnvjitlink. Search: conda-forge/win-64::*libnvjitlink*

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/win-64::libnvjitlink

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

</details>

**Comment by dholth** [comment] 2023-04-10 14:36
@barabo it makes sense to cache `.conda` but is it faster? Wouldn't the CDN sync usually be the first downloader of brand-new `.conda` packages from a cold cache?

**Comment by jakirkham** [comment] 2023-04-19 22:47
Noticing this with `cuda-nvcc` number `1` on `ppc64le`:

Package has been up for ~1.75hrs, but is not available from CDN (getting missing package errors when requesting it)

<details>
<summary>Screenshot:</summary>
<img width="1840" alt="Screen Shot 2023-04-19 at 3 45 11 PM" src="https://user-images.githubusercontent.com/3019665/233215741-de2c3d3a-e5c4-49a1-9d47-67a31d80155c.png">
</details>

**Comment by leofang** [comment] 2023-04-24 19:46
FYI it took >60 mins to reflect a simple channel label change: https://github.com/conda-forge/admin-requests/pull/710#issuecomment-1520547532

**Comment by beckermr** [comment] 2023-04-27 20:50
I want to chime in here that I am seeing CDN sync times on the conda-forge status page of over 15 minutes on a regular basis now.

**Comment by barabo** [comment] 2023-04-28 21:07
@dholth and I are going to sync on this early next week.  Something does seem to be going on - we'll get to the bottom of it.

**Comment by jakirkham** [comment] 2023-05-01 19:49
Thanks Carl! 🙏

Please let us know if you need anything 🙂

**Comment by dholth** [comment] 2023-05-01 19:52
We've shortened the cron interval so that update should happen more frequently. Keep an eye on it and we'll see whether any other part of the pipeline is delayed.

**Comment by barabo** [comment] 2023-05-01 21:22
The cron interval was every 10 minutes, which was fine when the job reliably ran in under 7 minutes.  It recently started going over 10 for some runs, so we shortened it to 2.

I'm still looking at the logs to see if there's a way to speed it up.

**Comment by jakirkham** [comment] 2023-05-01 22:24
Ok would be interested to know why the script is taking longer. AIUI there was some work in the past to cutdown the script runtime pretty significantly

**Comment by jezdez** [comment] 2023-05-15 08:53
Looking at this, I'm uncertain if we've come to a conclusion, @barabo do you think we can close this?

**Comment by jakirkham** [comment] 2023-05-15 21:07
Reading Carl's last comment, my (potentially incorrect) understanding is the cron job used for mirroring is starting to take longer. The cause for this is unknown and being investigated. So not yet fully resolved

**Comment by dholth** [comment] 2023-05-15 21:11
I'm not too worried about it yet. The cron job used to take 6-7 minutes, and now it sometimes takes a little longer (which would have caused a 10 minute delay in the past); but sometimes it still runs in < 10 minutes. We should try to vacuum the databases at least.

**Comment by jakirkham** [comment] 2023-05-15 21:19
If it is reliably mirroring at 10min intervals great, the issues mentioned above were when +1hr mirroring times were seen

**Comment by m3vaz** [comment] 2023-06-29 16:34
@jakirkham @leofang we're still seeing these issues with packages that were posted 23 hours ago e.g. [cuda-python](https://anaconda.org/nvidia/cuda-python/files?version=12.2.0).

**Comment by barabo** [comment] 2023-06-29 18:51
Looking into the `nvidia` clone worker right now.  It appears to have gotten stuck 18 hours ago and needed a restart.  I believe it's done updating now.

**Comment by m3vaz** [comment] 2023-06-29 19:32
@barabo Confirmed, I see the packages now.

Is there a way we could check on sync status for a given channel? (for when we hit similar issues in the future)

**Comment by barabo** [comment] 2023-06-29 19:40
I believe you can do something like this to get a sense for when a channel subdir was last updated.
```
curl -Is https://conda.anaconda.org/nvidia/linux-64/repodata.json | grep last-modified
last-modified: Thu, 29 Jun 2023 18:35:12 GMT
```

It won't work if there are no new packages in `linux-64` for that channel, but if you know that's what you're looking for it should be a good test.

**Comment by m3vaz** [comment] 2023-06-29 20:06
Can we assume that the update job takes ~10 minutes and is run every 10 minutes (as referenced earlier in the issue)?

**Comment by jakirkham** [comment] 2023-06-29 20:09
cc @adibbley (for awareness)

**Comment by barabo** [comment] 2023-06-30 15:05
`conda-forge` syncs every 10 minutes, but I think the `nvidia` channel (and a few others) only sync every 20 minutes.  We can look into increasing that cadence, if necessary.

**Comment by jakirkham** [comment] 2023-07-31 22:56
We are seeing this issue with the `nvidia` channel again. Could someone please take a look?

cc @raydouglass

**Comment by jezdez** [comment] 2023-08-01 10:23
@jakirkham we're looking into it

**Comment by jezdez** [comment] 2023-12-15 14:17
This was resolved at the time, closing.

**Closed by jezdez** 2023-12-15 14:17 UTC
Labels: type::bug
