### ISSUE TITLE
Conda-Forge CDN Outage

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#851] opened 2023-11-20 06:50 UTC
We are seeing an extended CDN outage in conda-forge. Please see screenshot below

![image]( https://github.com/conda/infrastructure/assets/3019665/72815469-1ad1-4506-9b6d-1574f8c02cd1 )

**Comment by h-vetinari** [comment] 2023-11-20 12:15
Seems we're coming back to normal... Thanks a lot for the quick help!

**Comment by barabo** [comment] 2023-11-20 16:02
There was a full-disk on the clone worker - @dholth and I will be making some changes later today that should eliminate this issue going forward.  We'll update this issue after that's complete.

**Comment by jakirkham** [comment] 2023-11-20 20:21
Thanks Carl & Jannis! 🙏

**Comment by barabo** [comment] 2023-11-20 21:42
We freed up 1.2 TB of cached `*.tar.bz2` package files from the local clone VM disk.  This will not affect their availability in the channel!  We also added a clean-up step to delete package filed from the local disk that are confirmed to be available in the CDN.  So, disk space should not be a problem for this stage of the CDN pipeline again.

**Comment by jakirkham** [comment] 2023-11-20 22:09
Thanks Carl! 🙏

That must have been a lot of `*.tar.bz` files. Were there `*.conda` files that needed cleaning up as well?

**Comment by dholth** [comment] 2023-11-20 22:15
We will be able to clean up all indexed and mirrored packages, but we have been cautious by removing mostly-older `.tar.bz2`

**Comment by jakirkham** [comment] 2023-11-20 22:40
Ok am wondering about `.conda` packages since that would likely cause a back up next (as conda-forge is mainly producing `.conda` packages atm)

**Comment by dholth** [comment] 2023-11-20 22:57
[This is the beginning of related conda-index work.](https://github.com/conda/conda-index/pull/130). This may or may not be the right way to go, but by separating the cache and packages directories we could index packages straight from fsspec or s3 or some other remote storage. Similarly the current CDN clone overrides https://github.com/conda/conda-index/blob/main/conda_index/index/sqlitecache.py#L425 so that the set of files-to-be-indexed does not hit the local filesystem.

**Comment by jezdez** [comment] 2023-12-15 14:12
I'm closing this particular infra issue since it seems to have been resolved for now.

**Closed by jezdez** 2023-12-15 14:12 UTC
