### ISSUE TITLE
`rss.xml` is broken on `bioconda`

### ISSUE THREAD

**Issue by jaimergp** [conda/infrastructure#866] opened 2024-01-03 17:29 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

https://conda.anaconda.org/bioconda/rss.xml is not valid RSS or even XML parsable. Its content seems to be a flat collection of `<item>` elements:

```
    <item>
  <title>running sync</title>
  <pubDate>03 Jan 2024 17:08:58 UTC</pubDate>
</item><item>
  <title>linux-64:add:bioconductor-bsseq-1.30.0-r41h399db7b_0.tar.bz2</title>
  <pubDate>08 Nov 2021 01:42:55 UTC</pubDate>
</item><item>
  <title>linux-64:add:bioconductor-fraser-1.6.0-r41h399db7b_0.tar.bz2</title>
  <pubDate>08 Nov 2021 01:42:55 UTC</pubDate>
</item>
    <item>
  <title>running sync</title>
  <pubDate>09 Nov 2021 03:09:56 UTC</pubDate>
</item>
```

But `conda-forge`'s RSS looks like this:

```
<?xml version="1.0" ?>
<rss version="2.0">
  <channel>
    <title>anaconda.org/conda-forge</title>
    <link>https://conda.anaconda.org/conda-forge</link>
    <description>The most recent 100 updates for conda-forge.</description>
    <pubDate>Wed, 03 Jan 2024 17:24:54 GMT</pubDate>
    <lastBuildDate>Wed, 03 Jan 2024 17:24:54 GMT</lastBuildDate>
    <item>
      <title>scikit-base 0.7.0 [linux-64, linux-aarch64, osx-64, osx-arm64, win-64]</title>
      <description>Base classes for sklearn-like parametric objects</description>
      <link>https://skbase.readthedocs.io/en/latest/</link>
      <comments>https://github.com/sktime/skbase</comments>
      <guid>https://pypi.io/packages/source/s/scikit-base/scikit-base-0.7.0.tar.gz</guid>
      <pubDate>Wed, 03 Jan 2024 17:07:57 GMT</pubDate>
      <source>https://github.com/sktime/skbase</source>
    </item>
...
```

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

### Additional Context

N/A

**Comment by jakirkham** [comment] 2024-03-19 19:22
Wonder if this shares the same root cause as the Bioconda CDN sync issue: https://github.com/conda/infrastructure/issues/895

**Comment by jaimergp** [comment] 2024-03-21 14:57
AFAIU, this is just the CDN backend for bioconda using an older conda-index stack.

**Comment by johanneskoester** [comment] 2024-03-22 13:23
Can it get an update please, so that hopefully the sync works again?

**Comment by morremeyer** [comment] 2024-09-16 11:02
We have updated the CDN sync process for all channels by now. Specifically for bioconda, this is the tracking issue: https://github.com/bioconda/bioconda-utils/issues/1008.

With these upgrades, the stack for all channels is the same now.

**Comment by jezdez** [comment] 2024-09-16 11:55
Closing as fixed via https://github.com/bioconda/bioconda-utils/issues/1008

**Closed by jezdez** 2024-09-16 11:55 UTC
Labels: type::bug

**Comment by jaimergp** [comment] 2024-09-17 12:41
Confirmed: https://conda-metadata-app.streamlit.app/?q=bioconda now works properly!
