### ISSUE TITLE
conda-forge repodata is missing new packages as of 2024-09-07

### ISSUE THREAD

**Issue by beckermr** [conda/infrastructure#1024] opened 2024-09-08 11:58 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

New packages are not appearing in the `conda-forge` repodata. See for example https://anaconda.org/conda-forge/conda-forge-feedstock-ops/files which is at 0.5.0 but conda search yeilds

```zsh
% conda search conda-forge-feedstock-ops
Loading channels: done
# Name                       Version           Build  Channel             
conda-forge-feedstock-ops           0.3.0    pyhd8ed1ab_1  conda-forge       
```

**Comment by beckermr** [comment] 2024-09-08 11:58
cc @jezdez @chenghlee

**Comment by jezdez** [comment] 2024-09-08 16:58
Looking

**Comment by jezdez** [comment] 2024-09-08 17:15
I've raised an incident internally to investigate ASAP, will keep you up-to-date

**Comment by morremeyer** [comment] 2024-09-08 19:02
Hey everyone,

at 2024-09-07T01:29:29 UTC, due to reasons we could not yet determine, the cloning process got stuck, leading to the clone job not terminating and therefore, no new jobs were started.

We have terminated the stuck job, and the next job updated the clone to 2024-09-08T18:52:26 UTC.

**Comment by morremeyer** [comment] 2024-09-08 19:34
The cloning has stabilized now. We will continue our root cause investigation tomorrow and implement measures to prevent this from happening again.

**Comment by morremeyer** [comment] 2024-09-09 11:50
To prevent the process from getting stuck and blocking subsequent runs, we have implemented a mechanism that terminates stuck jobs after 30 minutes earlier today, to ensure that if a job gets stuck again, the next job is unblocked. 

We have not yet identified the root cause for this issue and are continuing to look into it.

**Comment by morremeyer** [comment] 2024-09-12 08:08
Yes, with the code changes for the current version (v3) of the cloning, the implementation was changed to python `requests`, where we did not implement the timeouts initially.

This has been fixed with the changes I mentioned above.

**Closed** 2024-09-12 08:40 UTC
Labels: type::bug
