### ISSUE TITLE
Indexing for the CDN seems markedly slower on some architectures than others

### ISSUE THREAD

**Issue by h-vetinari** [conda/infrastructure#829] opened 2023-10-04 23:46 UTC
I noticed in recent days that the indexer for `osx-64` is markedly slower than for all the other arches. Most packages are available through the CDN in 15-20min, but osx often takes much longer, like 1-2h.

Not a huge issue, but noticeable during a migration (e.g. Python 3.12, Boost running at the moment).

As my most recent [example](https://anaconda.org/conda-forge/minizip/files) (I use `https://anaconda.org/conda-forge/<package>/files` as a proxy; once the download number jumps from 0 to 1, it only takes a couple more minutes for the package to be available, e.g. as verified by `mamba repoquery search <package> -c conda-forge -p <arch>`):

![image](https://github.com/conda/infrastructure/assets/33685575/f152ed9e-5191-49a3-a6bf-8d4ecb1eaa1f)

The other architectures in this example were all available in under 15-20 minutes.

PS: @jakirkham asked me to open an issue here after asking about this on element.

**Comment by h-vetinari** [comment] 2023-10-05 00:39
Two hours now:

![image](https://github.com/conda/infrastructure/assets/33685575/b5cbb2a9-d327-4f1c-80e1-10166b7c1081)

**Comment by jakirkham** [comment] 2023-10-05 23:30
@jezdez do you know who we should talk to about this?

**Comment by jakirkham** [comment] 2023-10-11 18:16
This is being investigated: https://github.com/conda/infrastructure/issues/836#issuecomment-1758053093

**Comment by jezdez** [comment] 2023-12-15 14:15
Closing as a duplicate of #836.

**Closed by jezdez** 2023-12-15 14:15 UTC
